server:
  port: 8080
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      mvc:
        routes:
          - id: order-service
            uri: lb://order-service
            predicates:
              - Path=/api/v1/order/**
          - id: inventory-service
            uri: lb://inventory-service
            predicates:
              - Path=/api/v1/inventory/**
